version: '3'
services:
  db:
    image: mysql:5.7.22
    ports:
    - "3306:3306"
    volumes:
    - chickmysql:/var/lib/mysql
    - "./sql/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: chick
      MYSQL_USER: chick
      MYSQL_PASSWORD: chick
      MYSQL_DATABASE: chick

volumes:
  chickmysql:
    driver: local
